# Default base image: nanoserver-1909 (build 18363) for old Win10 dev machines.
# Process isolation requires an EXACT OS build match between host and container.
# CI (windows-2022, build 20348) overrides this via:
#   --build-arg BASE_IMAGE=mcr.microsoft.com/powershell:nanoserver-ltsc2022
# See Run-ContainerTests.ps1 -BaseImage parameter.
ARG BASE_IMAGE=mcr.microsoft.com/powershell:nanoserver-1909
FROM ${BASE_IMAGE}
WORKDIR C:/toolset-repo
COPY . .
ENTRYPOINT ["pwsh", "-File", "tests/Invoke-ContainerTests.ps1"]
