name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  update-tests:
    name: Update mode tests
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/validate-and-test
